-- Coach Dean v2.0 schema additions
-- Adds fields needed for complement positioning: training tools, terrain,
-- per-activity weather, and plan provenance tracking.

-- training_profiles: capture what tools the athlete already uses and terrain preference.
-- These inform how Dean interprets effort and what coaching context is relevant.
ALTER TABLE training_profiles
  ADD COLUMN IF NOT EXISTS training_tools text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS terrain_type text;  -- 'road' | 'trail' | 'mixed'

-- activities: store historical weather at run time (fetched from Open-Meteo archive
-- after each Strava sync). weather_fetched_at = null means not yet fetched or no
-- location data available.
ALTER TABLE activities
  ADD COLUMN IF NOT EXISTS start_lat float,
  ADD COLUMN IF NOT EXISTS start_lng float,
  ADD COLUMN IF NOT EXISTS weather_data jsonb,
  ADD COLUMN IF NOT EXISTS weather_fetched_at timestamptz;

-- training_plans: track whether a plan was generated by Dean, uploaded by the user,
-- or described by the user in natural language. raw_plan_text preserves the original
-- for reference.
ALTER TABLE training_plans
  ADD COLUMN IF NOT EXISTS plan_source text NOT NULL DEFAULT 'generated',
  ADD COLUMN IF NOT EXISTS raw_plan_text text;

-- Backfill existing training_plans rows as 'generated'
UPDATE training_plans SET plan_source = 'generated' WHERE plan_source IS NULL OR plan_source = '';
