name: Tests

on:
  push:
    branches: ["**"]
  pull_request:
  schedule:
    # Every 3 days at 9:07am UTC
    - cron: "7 9 */3 * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
